# This compose file uses two containers built from the NIST-ACE repository. Run the following commands prior
# to starting the docker compose deployment.
#
# docker build -t datamachines/nist-ace .
#
# cd lang/python/examples/analytics/opencv_object_detector && docker build -t ocv-ssd .


version: "2"
services:
  # ACE SERVICES
  ace:
    image: datamachines/nist-ace:demo
    restart: always
    command:
      - "tail" 
      - "-f" 
      - "/dev/null"

  api-server:  
   image: datamachines/ace-ui:demo
   restart: always
   volumes:
    #  - "./run.py:/ace-ui/run.py"  # Uncomment to test demo changes
     - "./docker-compose.yml:/ace-ui/static/docker-compose.yml"
     - "./static/settings.yml:/ace-ui/static/settings.yml"
   ports: 
     - "5000:5000"
    
  opencv-object-detector:
    image: ocv-ssd:demo
    restart: always
    labels:
      type: analytics
    command:    
      - "--verbose"

  ssd-mobilenet-object-detector:
    image: ocv-ssd:demo
    restart: always
    labels:
      type: analytics
    command:    
      - "--verbose"

  act_detector:
    image: act-recognition:demo
    labels:
      type: analytics
    restart: always
    ports:
      - "3333:3000"

  nats_server:
    image: nats:2.1.9
    restart: always
    ports: 
      - "4222:4222"


# DATABASE AND GRAFANA VISUALIZATION SERVICES
  influxdb:
    image: influxdb:1.7
    restart: always
    ports:
        - "8086:8086"
    volumes:
        - influxdb-storage:/var/lib/influxdb
    environment:
        INFLUXDB_DB: ace
  grafana:
    image: grafana/grafana
    restart: always
    ports:
        - "8088:3000"
    depends_on:
        - influxdb
    volumes:
        - grafana-storage:/var/lib/grafana
  

# Additional Video Streams
  video_file_1:
    image: video_server:demo
    restart: always
    labels:
      type: video
    volumes:
      - $PWD:/videos
    ports:
        - "6420:6420"
    command:
      - "-v"
      - "/videos/{video filename}"      # Put your video file name here

  video_file_2:
    image: video_server:demo
    restart: always
    labels:
      type: video
    volumes:
      - $PWD:/videos
    ports:
        - "6421:6421"
    command:
      - "-v"
      - "/videos/{video filename}"      # Put your video file name here
      - "-p"
      -  6421
volumes:
  grafana-storage:
    external: true
  influxdb-storage:
    external: true
